# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases
  - 7.0
  - 7.1
  - 7.2
  - hhvm
env:
  - DB=mysql


# execute any number of scripts before the test run, custom env's are available as variables
before_script:
    - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS hello_world_test;" -uroot; fi

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
# script:
#     - phpunit --configuration phpunit_$DB.xml --coverage-text

# before_script:
#     - "COMPOSER_ALLOW_XDEBUG=1"
#     - composer install --no-interaction
#
# # Testing the app (see phpunit.xml) for configs, generating Code Coverage report
 script:
   -phpunit Tests/HelloWorldTest

# Monitor only these branches
branches:
  only:
  - master
  - test
